// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "uzuto-20191117155723-hostingbucket-devdd",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1psx3fwg1hbwe.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:b2fd03e3-6d00-4ede-9ed9-e61567cc7b89",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_66YstZUQa",
    "aws_user_pools_web_client_id": "6p8d1dgs79frv6q63vr8sgng6h",
    "oauth": {
        "domain": "uzutofc7d8597-fc7d8597-devdd.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://bigvxgmx4ba2jn273j44uy5bxy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-sx2upf2j65euzc3kgtpycylugq",
    "aws_user_files_s3_bucket": "uzutostoragebucket-devdd",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
